---
ID: "21fee090-3ace-4f6f-9f97-cc8db4a4389f"
Parent: "c330d166-687f-48c1-8fbc-47de306d34d6"
Template: "c330d166-687f-48c1-8fbc-47de306d34d6"
Path: /sitecore/templates/Ignition/Fields/Related/SecondaryLink/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150326T151449Z
